# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dff210b04cc21a9cfbfc7b51ffe93e0c5989886522ac746ff4fb6b76c0a35d5f1129d9faece05ccd3db184a853f574e13c906c1edfc73873318d569a8362249

test:
  secret_key_base: 8324b876433d31a577cdf8674c9b87c76b8637339ddc0f7d2f332ffce878e51ab002904b87e6d9ffbf0ca548a85932e04d9ed2d7c6865f4ea5d51983fe8f65d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
